### ISSUE TITLE
Nav2 FollowWaypoints action does not work

### ISSUE THREAD

**Issue by diegoplanchenstainer** [bonnybabukachappilly/ros2bridge#1]
Hi, I'm trying to use your code to send the FollowWaypoints action of Nav2 to ROS. With NavigateToPose action works fine, however when sending FollowWaypoints action the code crashes and the client disconnects.

Here the steps to reproduce the error:

I start the program with:

`python -m ros2bridge -p 9090 -n`
and returns:
```
Websocket started: 'ws://*:9090'
Client connected: client_985ad2c67329ef08
```

Init action client:
```json
{
	"operation": "action_client",
	"action": "create",
	"action_name": "/robot1/follow_waypoints",
	"action_type": "nav2_msgs/FollowWaypoints"
}
```
which returns:
```
Client: client_985ad2c67329ef08 created a action client. | Action Name: /robot1/follow_waypoints | Type: nav2_msgs/FollowWaypoints
```

Then send the action:
```json
{
	"operation": "action_client",
	"action": "call",
	"action_name": "/robot1/follow_waypoints",
	"action_type": "nav2_msgs/FollowWaypoints",
	"message": {
		"poses": [
			{
				"header": {
					"stamp": {
						"sec": 324,
						"nanosec": 355000000
					},
					"frame_id": "map"
				},
				"pose": {
					"position": {
						"x": 153.85197596133244,
						"y": 6.408348422589976,
						"z": 0.010167012762176242
					},
					"orientation": {
						"x": 0.0003170579113323778,
						"y": -0.000676868286006515,
						"z": -0.1263032685284976,
						"w": 0.9919913939559266
					}
				}
			},
			{
				"header": {
					"stamp": {
						"sec": 324,
						"nanosec": 355000000
					},
					"frame_id": "map"
				},
				"pose": {
					"position": {
						"x": 163.85197596133244,
						"y": 6.408348422589976,
						"z": 0.010167012762176242
					},
					"orientation": {
						"x": 0.0003170579113323778,
						"y": -0.000676868286006515,
						"z": -0.1263032685284976,
						"w": 0.9919913939559266
					}
				}
			}
		]
	}
}
```

Here the program returns this error:
```
Uncaught exception GET / (172.20.0.1)
HTTPServerRequest(protocol='http', host='localhost:9090', method='GET', uri='/', version='HTTP/1.1', remote_ip='172.20.0.1')
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tornado/websocket.py", line 635, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/ubuntu/ros2bridge/src/ros2bridge/server/ws_server.py", line 88, in on_message
    route_message(_client, message)  # type: ignore [arg-type]
  File "/home/ubuntu/ros2bridge/src/ros2bridge/server/route_message.py", line 76, in route_message
    _operation.handle_operation(_msg)
  File "/home/ubuntu/ros2bridge/src/ros2bridge/operations/action_client.py", line 83, in handle_operation
    goal = self.data_parser.pack_data_to_ros(
  File "/home/ubuntu/ros2bridge/src/ros2bridge/utils/data_parser.py", line 149, in pack_data_to_ros
    setattr(module, dict_key, value)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/nav2_msgs/action/_follow_waypoints.py", line 130, in poses
    assert \
AssertionError: The 'poses' field must be a set or sequence and each value of type 'PoseStamped'
ROS Node: client_985ad2c67329ef08 terminated.
Client: client_985ad2c67329ef08 disconnected.
```

It seems that pack_data_to_ros() is not able to cope with lists as the one required by FollowWaypoints. could you please check on that? Or is my websocket action call message wrong?

**Comment by bonnybabukachappilly** [comment]
Sorry for the late replay. I will look into it.

**Comment by bonnybabukachappilly** [comment]
Hey @diegoplanchenstainer 
This library depends on ros packages structure. When ws client request something, it matches with ros and process the request. In your case FollowWaypoints only asks that the goal should be a list. But It should be a set of PoseStamped messages.
```
AssertionError: The 'poses' field must be a set or sequence and each value of type 'PoseStamped'
```
I tried to make something like that, but it didn't work. I will try with pure ros code without ws. If any thing comes up I will update the package.

**Comment by bonnybabukachappilly** [comment]
I have made a temporary Fix. I will look for a more permanent fix later. Please update the package once I close this issue.

**Comment by bonnybabukachappilly** [comment]
Please update to the new version.
